namespace HelloWorld.Constants;
public static class AppConstants
{
    public static readonly string SeparationLines = new('-', 10);

    public static readonly Dictionary<string, string> CountryNationalities = new()
    {
        { "AF", "Afghan" },
        { "AL", "Albanian" },
        { "DZ", "Algerian" },
        { "AS", "American Samoan" },
        { "AD", "Andorran" },
        { "AO", "Angolan" },
        { "AG", "Antiguan or Barbudan" },
        { "AR", "Argentine" },
        { "AM", "Armenian" },
        { "AU", "Australian" },
        { "AT", "Austrian" },
        { "AZ", "Azerbaijani" },
        { "BS", "Bahamian" },
        { "BH", "Bahraini" },
        { "BD", "Bangladeshi" },
        { "BB", "Barbadian" },
        { "BY", "Belarusian" },
        { "BE", "Belgian" },
        { "BZ", "Belizean" },
        { "BJ", "Beninese" },
        { "BT", "Bhutanese" },
        { "BO", "Bolivian" },
        { "BA", "Bosnian or Herzegovinian" },
        { "BW", "Botswanan" },
        { "BR", "Brazilian" },
        { "BN", "Bruneian" },
        { "BG", "Bulgarian" },
        { "BF", "Burkinabe" },
        { "BI", "Burundian" },
        { "CV", "Cabo Verdean" },
        { "KH", "Cambodian" },
        { "CM", "Cameroonian" },
        { "CA", "Canadian" },
        { "KY", "Caymanian" },
        { "CF", "Central African" },
        { "TD", "Chadian" },
        { "CL", "Chilean" },
        { "CN", "Chinese" },
        { "CO", "Colombian" },
        { "KM", "Comorian" },
        { "CG", "Congolese (Congo-Brazzaville)" },
        { "CD", "Congolese (Congo-Kinshasa)" },
        { "CR", "Costa Rican" },
        { "HR", "Croatian" },
        { "CU", "Cuban" },
        { "CY", "Cypriot" },
        { "CZ", "Czech" },
        { "DK", "Danish" },
        { "DJ", "Djiboutian" },
        { "DM", "Dominican" },
        { "DO", "Dominican" },
        { "EC", "Ecuadorian" },
        { "EG", "Egyptian" },
        { "SV", "Salvadoran" },
        { "GQ", "Equatorial Guinean" },
        { "ER", "Eritrean" },
        { "EE", "Estonian" },
        { "ET", "Ethiopian" },
        { "FJ", "Fijian" },
        { "FI", "Finnish" },
        { "FR", "French" },
        { "GA", "Gabonese" },
        { "GM", "Gambian" },
        { "GE", "Georgian" },
        { "DE", "German" },
        { "GH", "Ghanaian" },
        { "GR", "Greek" },
        { "GD", "Grenadian" },
        { "GT", "Guatemalan" },
        { "GN", "Guinean" },
        { "GW", "Bissau-Guinean" },
        { "GY", "Guyanese" },
        { "HT", "Haitian" },
        { "HN", "Honduran" },
        { "HU", "Hungarian" },
        { "IS", "Icelandic" },
        { "IN", "Indian" },
        { "ID", "Indonesian" },
        { "IR", "Iranian" },
        { "IQ", "Iraqi" },
        { "IE", "Irish" },
        { "IL", "Israeli" },
        { "IT", "Italian" },
        { "JM", "Jamaican" },
        { "JP", "Japanese" },
        { "JO", "Jordanian" },
        { "KZ", "Kazakh" },
        { "KE", "Kenyan" },
        { "KI", "Kiribati" },
        { "KP", "North Korean" },
        { "KR", "South Korean" },
        { "KW", "Kuwaiti" },
        { "KG", "Kyrgyz" },
        { "LA", "Lao" },
        { "LV", "Latvian" },
        { "LB", "Lebanese" },
        { "LS", "Basotho" },
        { "LR", "Liberian" },
        { "LY", "Libyan" },
        { "LI", "Liechtenstein" },
        { "LT", "Lithuanian" },
        { "LU", "Luxembourg" },
        { "MG", "Malagasy" },
        { "MW", "Malawian" },
        { "MY", "Malaysian" },
        { "MV", "Maldivian" },
        { "ML", "Malian" },
        { "MT", "Maltese" },
        { "MH", "Marshallese" },
        { "MR", "Mauritanian" },
        { "MU", "Mauritian" },
        { "MX", "Mexican" },
        { "FM", "Micronesian" },
        { "MD", "Moldovan" },
        { "MC", "Monacan" },
        { "MN", "Mongolian" },
        { "ME", "Montenegrin" },
        { "MA", "Moroccan" },
        { "MZ", "Mozambican" },
        { "MM", "Burmese" },
        { "NA", "Namibian" },
        { "NR", "Nauruan" },
        { "NP", "Nepalese" },
        { "NL", "Dutch" },
        { "NZ", "New Zealander" },
        { "NI", "Nicaraguan" },
        { "NE", "Nigerien" },
        { "NG", "Nigerian" },
        { "NO", "Norwegian" },
        { "OM", "Omani" },
        { "PK", "Pakistani" },
        { "PW", "Palauan" },
        { "PA", "Panamanian" },
        { "PG", "Papua New Guinean" },
        { "PY", "Paraguayan" },
        { "PE", "Peruvian" },
        { "PH", "Filipino" },
        { "PL", "Polish" },
        { "PR", "Puerto Rican" },
        { "PT", "Portuguese" },
        { "QA", "Qatari" },
        { "RO", "Romanian" },
        { "RU", "Russian" },
        { "RW", "Rwandan" },
        { "KN", "Saint Kitts and Nevis" },
        { "LC", "Saint Lucian" },
        { "VC", "Saint Vincentian" },
        { "WS", "Samoan" },
        { "SM", "San Marinese" },
        { "ST", "Sao Tomean" },
        { "SA", "Saudi" },
        { "SN", "Senegalese" },
        { "RS", "Serbian" },
        { "SC", "Seychellois" },
        { "SL", "Sierra Leonean" },
        { "SG", "Singaporean" },
        { "SK", "Slovak" },
        { "SI", "Slovenian" },
        { "SB", "Solomon Islander" },
        { "SO", "Somali" },
        { "ZA", "South African" },
        { "SS", "South Sudanese" },
        { "ES", "Spanish" },
        { "LK", "Sri Lankan" },
        { "SD", "Sudanese" },
        { "SR", "Surinamese" },
        { "SZ", "Eswatini" },
        { "SE", "Swedish" },
        { "CH", "Swiss" },
        { "SY", "Syrian" },
        { "TW", "Taiwanese" },
        { "TJ", "Tajik" },
        { "TZ", "Tanzanian" },
        { "TH", "Thai" },
        { "TL", "Timorese" },
        { "TG", "Togolese" },
        { "TO", "Tongan" },
        { "TT", "Trinidadian or Tobagonian" },
        { "TN", "Tunisian" },
        { "TR", "Turkish" },
        { "TM", "Turkmen" },
        { "TV", "Tuvaluan" },
        { "UG", "Ugandan" },
        { "UA", "Ukrainian" },
        { "AE", "Emirati" },
        { "GB", "British" },
        { "US", "American" },
        { "UY", "Uruguayan" },
        { "UZ", "Uzbek" },
        { "VU", "Vanuatuan" },
        { "VE", "Venezuelan" },
        { "VN", "Vietnamese" },
        { "YE", "Yemeni" },
        { "ZM", "Zambian" },
        { "ZW", "Zimbabwean" }
    };
}